#!/bin/bash
set -o xtrace

mkdir GitHub
cd GitHub
git clone https://github.com/webrtc/KITE.git
cd KITE
git checkout e9296165cd24bea92cddb59f2bf211c99f764d58

wget https://downloads.apache.org/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.zip
unzip apache-maven-3.6.3-bin.zip
mv apache-maven-3.6.3 ~
rm -f apache-maven-3.6.3-bin.zip
#This is a temporary hack since maven 3.8.1 which is the default for GitHub Action VM does not work with kite
export PATH=~/apache-maven-3.6.3/bin:$PATH
source ~/.bashrc
echo `mvn --version`

chmod +x configureLinux.sh
yes n | ./configureLinux.sh

cd KITE-AppRTC-Test
../scripts/linux/path/c all