#!/bin/bash
set -o xtrace

mkdir GitHub
cd GitHub
git clone https://github.com/webrtc/KITE.git
cd KITE
git checkout 498934fc774e8ae1bf9908a302a8e497973bb726

chmod -R +x scripts/linux
printf "n\n3.6.3" | ./scripts/linux/installMaven.sh
#This is a temporary hack since maven 3.8.1 which is the default for GitHub Action VM does not work with kite
export PATH=~/apache-maven-3.6.3/bin:$PATH
source ~/.bashrc
echo `mvn --version`

chmod +x configureLinux.sh
yes n | ./configureLinux.sh

cd KITE-AppRTC-Test
../scripts/linux/path/c all