#!/bin/bash
set -o xtrace

cd ~/build

mkdir GitHub
cd GitHub
git clone https://github.com/webrtc/KITE.git
cd KITE
git checkout e9296165cd24bea92cddb59f2bf211c99f764d58

chmod -R +x scripts/linux

chmod +x configureLinux.sh
yes n | ./configureLinux.sh

cd KITE-AppRTC-Test
../scripts/linux/path/c all > /dev/null
