#!/usr/bin/env node

// eslint-disable-next-line @typescript-eslint/no-var-requires
const fs = require('fs');
// eslint-disable-next-line @typescript-eslint/no-var-requires
const path = require('path');

var myArgs = process.argv.slice(2);
var test_config_path = "";
if(myArgs[0] === "browserCompatibility")    {
    console.log("Using browser compatibility test configs for setting userArn");
    test_config_path = path.join(__dirname, '..', '..', 'configs', 'browserCompatibilityTest', 'messaging_session_test.config.json');
}
else    {
    console.log("Using integration test configs for setting userArn");
    test_config_path = path.join(__dirname, '..', '..', 'configs', 'integrationTest', 'messaging_session_test.config.json');
}
const test_config_file = fs.readFileSync(test_config_path);

const test_config = JSON.parse(test_config_file);

console.log("Setting userArn in the request payload");
test_config.tests[0].payload.userArn = process.env.MESSAGING_USER_ARN;
fs.writeFileSync(test_config_path, JSON.stringify(test_config, null, 2));