#!/bin/bash

echo "Uploading logs to S3"
run_id=$JOB_ID-$(date +%s)
s3_bucket="amazon-chime-sdk-js-integration-test-github-action-logs"

function put_in_s3 {
    aws s3 sync $GITHUB_WORKSPACE/$1 s3://$s3_bucket/$JOB_ID/$2 > /dev/null
}

put_in_s3 integration/logs test_logs
put_in_s3 integration/kite-allure-reports test_result

echo "View the results of the integration tests by using the following commands"
echo "[1] To view results for this build: "
echo "./script/get-integration-test-results --id " $run_id
echo "[2] To view results for all build: "
echo "./script/get-integration-test-results --all"
