#!/bin/bash
set -euxo pipefail

cd $GITHUB_WORKSPACE/demos/browser
npm run build
npm run build --app=meetingReadinessChecker

cd $GITHUB_WORKSPACE/demos/serverless
npm ci

echo "Deploying to alpha stage for canary"
npm run deploy -- -b chime-sdk-demo-canary -s chime-sdk-demo-canary -t -l
npm run deploy -- -b chime-sdk-meeting-readiness-checker-dev-canary -s chime-sdk-meeting-readiness-checker-dev-canary -a meetingReadinessChecker -t -l

echo "Deploying to gamma stage for canary that talks to prod Chime endpoint"
export AWS_ACCESS_KEY_ID=$GAMMA_AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$GAMMA_AWS_SECRET_ACCESS_KEY
npm run deploy -- -b chime-sdk-demo-gamma-canary -s chime-sdk-demo-gamma-canary -t -l
npm run deploy -- -b chime-sdk-meeting-readiness-checker-gamma-canary -s chime-sdk-meeting-readiness-checker-gamma-canary -a meetingReadinessChecker -t -l

echo "Deploying to beta stage for canary that talks to gamma Chime endpoint"
export AWS_ACCESS_KEY_ID=$BETA_AWS_ACCESS_KEY_ID
export AWS_SECRET_ACCESS_KEY=$BETA_AWS_SECRET_ACCESS_KEY
npm run deploy -- -b chime-sdk-demo-beta-canary -s chime-sdk-demo-beta-canary -c $GAMMA_CHIME_ENDPOINT -t -l
npm run deploy -- -b chime-sdk-meeting-readiness-checker-beta-canary -s chime-sdk-meeting-readiness-checker-beta-canary -a meetingReadinessChecker -c $GAMMA_CHIME_ENDPOINT -t -l
