#!/usr/bin/env ruby

Dir.chdir(File.expand_path(File.join(File.dirname(__FILE__), '..')))

def verbose command
  puts "--> #{command}"
  system(command) || fail("Failed: #{command}")
end

['SignalingProtocol'].each do |protocol|
  dir = protocol.downcase

  # please change the protobuf dependency in package.json to the following:
  # "protobufjs": "git://github.com/VitalyName/protobuf.js.git#236a7c757a5eada7926fdff149d0b49ada838275"
  # This is a walkaround for https://github.com/protobufjs/protobuf.js/issues/1414

  verbose "rm -rf src/#{dir}"
  verbose "mkdir -p src/#{dir}"

  # workaround for https://github.com/hegemonic/requizzle/issues/5
  # node@14 will work with libicu4c 72
  # verbose "brew install node@14"
  node = "#{`brew --prefix node@14`.strip}/bin/node"

  # workaround for https://github.com/protobufjs/protobuf.js/issues/1217
  # brew upgrade icu4c if library not loaded
  verbose "#{node} node_modules/.bin/pbjs -t static-module -w commonjs -o src/#{dir}/#{protocol}.js ./protocol/#{protocol}.proto"
  File.write('node_modules/protobufjs/package.json', File.read('node_modules/protobufjs/package.json').gsub('"jsdoc": "^3.6.3",', '"jsdoc": "~3.5.5",'))

  verbose "#{node} node_modules/.bin/pbjs -t static-module -w commonjs -o src/#{dir}/#{protocol}.js ./protocol/#{protocol}.proto"
  verbose "#{node} node_modules/.bin/pbts -o src/#{dir}/#{protocol}.d.ts src/#{dir}/#{protocol}.js"
end
