#!/bin/bash
set -euxo pipefail

cd $GITHUB_WORKSPACE/demos/serverless
npm ci

case $NAME in

ChimeProd)
    echo "Deploying to prod stage for canary that talks to prod Chime client"

    # Uses Chime Client
    npm run deploy -- -b chime-sdk-demo-prod-canary -o chime-sdk-demo-prod-canary -s chime-sdk-demo-prod-canary -u false -t -l
    npm run deploy -- -b chime-sdk-meeting-readiness-checker-prod-canary -s chime-sdk-meeting-readiness-checker-prod-canary -a meetingReadinessChecker -u false -t -l
    ;;

ChimeSDKMeetingsProdIAD)
    echo "Deploying to prod stage for canary that talks to prod IAD ChimeSDKMeetings client"

    # Uses ChimeSDKMeetings client
    npm run deploy -- -r us-east-1 -b chime-sdk-meetings-demo-prod-canary-us-east-1 -o chime-sdk-meetings-iad-demo-prod-canary -s chime-sdk-meetings-demo-prod-canary-us-east-1 -t -l
    ;;

ChimeSDKMeetingsProdPDX)
    echo "Deploying to prod stage for canary that talks to prod PDX ChimeSDKMeetings client"

    # Uses ChimeSDKMeetings client
    npm run deploy -- -r us-west-2 -b chime-sdk-meetings-demo-prod-canary-us-west-2 -o chime-sdk-meetings-pdx-demo-prod-canary -s chime-sdk-meetings-demo-prod-canary-us-west-2 -t -l
    ;;

ChimeSDKMeetingsProdFRA)
    echo "Deploying to prod stage for canary that talks to prod FRA ChimeSDKMeetings client"

    # Uses ChimeSDKMeetings client
    npm run deploy -- -r eu-central-1 -b chime-sdk-meetings-demo-prod-canary-eu-central-1 -o chime-sdk-meetings-fra-demo-prod-canary -s chime-sdk-meetings-demo-prod-canary-eu-central-1 -t -l
    ;;

ChimeSDKMeetingsProdSIN)
    echo "Deploying to prod stage for canary that talks to prod SIN ChimeSDKMeetings client"

    # Uses ChimeSDKMeetings client
    npm run deploy -- -r ap-southeast-1 -b chime-sdk-meetings-demo-prod-canary-ap-southeast-1 -o chime-sdk-meetings-sin-demo-prod-canary -s chime-sdk-meetings-demo-prod-canary-ap-southeast-1 -t -l
    ;;

esac