#!/usr/bin/env ruby
require 'json'

def verbose command
  puts("--> #{command}") || system(command) || fail("Failed: #{command}")
end

Dir.chdir(File.expand_path(File.join(File.dirname(__FILE__), '..')))
base = File.read('.base-branch').strip
commits = `git rev-list #{base}..`.strip.split("\n")

if commits.size == 0
  puts "OK: branch is equal with #{base}"
  exit 0
end

changelog = `git diff #{base}.. CHANGELOG.md`.strip
if changelog.length == 0
  STDERR.puts "No CHANGELOG.md entries since #{base}."
  exit 1
end

# Pull in package fixes automatically.
verbose('npm audit fix')

