#!/usr/bin/env ruby

versions = `npm view amazon-chime-sdk-js versions --json`.strip.split("\n")
# The output would be something like
#[
#  "1.0.0",
#  ...
#  "2.8.0", <- previous version
#  "2.9.0"  <- latest version
#]
puts versions[versions.size-3][3..-3]