  name: Miscellaneous Integration Workflow

  on:
    pull_request:
      branches:
        - main
        - 'release-**.x'

  env:
    SELENIUM_GRID_PROVIDER: saucelabs
    CLOUD_WATCH_METRIC: false
    TEST_TYPE: Integration-Test
    SAUCE_USERNAME: ${{secrets.SAUCE_USERNAME}}
    SAUCE_ACCESS_KEY: ${{secrets.SAUCE_ACCESS_KEY}}

  jobs:
    integ-data-message:
      name: Miscellaneous Integration Test
      runs-on: ubuntu-latest

      steps:
        - name: Checkout Package
          uses: actions/checkout@v2
          with:
            fetch-depth: 0
        - name: Pack the Chime SDK and install the tarball into the Demo
          run: |
            current_version=$(.github/script/get-current-version)
            echo "Packing current version:" $current_version
            npm run build
            npm pack
            cd demos/browser
            npm uninstall amazon-chime-sdk-js
            npm install ../../amazon-chime-sdk-js-$current_version.tgz
        - name: Check if needed to run
          id: test_needed
          run: |
            source ${GITHUB_WORKSPACE}/integration/js/script/need-integ-test
            check_if_integ_tests_required
            echo ::set-output name=integ_test_required::$requires_integration_test
        - name: Create a Job ID
          id: create-job-id
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          uses: filipstefansson/uuid-action@ce29ebbb0981ac2448c2e406e848bfaa30ddf04c
        - name: Set JOB_ID Env Variable
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          run: echo "JOB_ID=${{ steps.create-job-id.outputs.uuid }}" >> $GITHUB_ENV
        - name: Echo Job ID
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          run: echo "${{ steps.create-job-id.outputs.uuid }}"
        - name: Configure AWS Credentials
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          uses: aws-actions/configure-aws-credentials@v1
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1
        - name: Setup Sauce Connect
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          uses: saucelabs/sauce-connect-action@v1
          with:
            username: ${{ secrets.SAUCE_USERNAME }}
            accessKey: ${{ secrets.SAUCE_ACCESS_KEY }}
            noSSLBumpDomains: all
            tunnelIdentifier: ${{ steps.create-job-id.outputs.uuid }}
        - name: Setup Node.js - 20.x
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          uses: actions/setup-node@v1
          with:
            node-version: 20.x
        - name: Install Kite
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          run: integration/js/script/install-kite
        - name: Clean Install
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          run: npm ci
        - name: Run Data Message Integration Test
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          run: npm run test:integration-data-message
        - name: Run Meeting Readiness Checker Integration Test
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          run: npm run test:integration-meeting-readiness-checker
        - name: Run Meeting End Integration Test
          if:  steps.test_needed.outputs.integ_test_required == 'true'
          run: npm run test:integration-meeting-end