name: Publish
# When a new Github Release is created, publish to NPM
on:
  release:
    types: [published]

permissions:
  id-token: write  # Required for OIDC
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Package
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Setup Node environment
        uses: actions/setup-node@v4
        with:
          node-version: '26'
          registry-url: 'https://registry.npmjs.org'
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - name: NPM Install
        run: npm install
      - name: NPM run build
        run: npm run build
      - name: Get npm tag name
        id: npm_tag
        run: |
          npm_publish_tag=$(.github/script/get-npm-tag.js)
          echo "Received NPM publish tag:" $npm_publish_tag
          echo "npm_tag=$npm_publish_tag" >> $GITHUB_OUTPUT
      - name: Publish to NPM with tag
        run: npm publish --tag ${{ steps.npm_tag.outputs.npm_tag }}
